export const dataGenres = [
  "Fiction",
  "Adventure",
  "Mythology",
  "Action",
  "Romance",
  "Thriller",
];
export const dataAuthors = [
  "Jane Austen",
  "George Martin",
  "Jane Austen",
  "Jane Austen",
  "Jane Austen",
  "Jane Austen",
];
export const dataBooks = [
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },
  {
    title: "Kuyucakli Yusuf",
    author: "Sabahattin Ali",
    location: "Urla, İzmir - Urla Halk Kütüp.",
    seller: "Berke Udunman",
    price:50,
  },

];
